//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoMedia_Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArchivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblArchivo()
        {
            this.tblRegistroAlquilers = new HashSet<tblRegistroAlquiler>();
        }
    
        public int idArchivo { get; set; }
        public string titulo { get; set; }
        public Nullable<int> idTipoFile { get; set; }
        public string formato { get; set; }
        public Nullable<decimal> precio { get; set; }
        public string ruta { get; set; }
        public string detalles { get; set; }
        public string sinopsis { get; set; }
        public Nullable<int> codCategoria { get; set; }
    
        public virtual tblCategoria tblCategoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRegistroAlquiler> tblRegistroAlquilers { get; set; }
        public virtual tblTiposFile tblTiposFile { get; set; }
    }
}
