//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoMedia_Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRegistroAlquiler
    {
        public int codAlquiler { get; set; }
        public Nullable<System.DateTime> fecha_alquiler { get; set; }
        public Nullable<decimal> subTotal { get; set; }
        public Nullable<decimal> costoTotal { get; set; }
        public Nullable<int> idArchivo { get; set; }
        public Nullable<int> idUsuario { get; set; }
    
        public virtual tblArchivo tblArchivo { get; set; }
        public virtual tblUsuario tblUsuario { get; set; }
    }
}
